experiments:
- config: configs/h7/v36/resnet18_none_grouped_v2.yaml
  seed: 0
- config: configs/h7/v36/resnet18_none_grouped_v2.yaml
  seed: 1
- config: configs/h7/v36/resnet18_none_grouped_v2.yaml
  seed: 2
- config: configs/h7/v36/resnet18_none_grouped_v2_trainclean.yaml
  seed: 0
- config: configs/h7/v36/resnet18_none_grouped_v2_trainclean.yaml
  seed: 1
- config: configs/h7/v36/resnet18_none_grouped_v2_trainclean.yaml
  seed: 2
- config: configs/h7/v36/resnet18_lstm_L4_grouped_v2_trainclean.yaml
  seed: 0
- config: configs/h7/v36/resnet18_lstm_L4_grouped_v2_trainclean.yaml
  seed: 1
- config: configs/h7/v36/resnet18_lstm_L4_grouped_v2_trainclean.yaml
  seed: 2
- config: configs/h7/v36/resnet18_transformer_L16_crossfocal7_evalfix_grouped_v2_trainclean.yaml
  seed: 2
