#!/usr/bin/env python3
"""Render only the v23 event configs; never regenerate/delete historical sweeps."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
PARENT = "resnet18_transformer_L16_crossfocal7_recipe_e20_evalfix_split0"
PREFIX = "resnet18_transformer_L16_crossfocal7_recipe_event"


def render_configs() -> dict[str, str]:
    """Return repository-relative filenames and deterministic YAML contents."""
    docs = {}
    header = (
        "# v23 /. Generated by scripts/make_h7_event_configs.py.\n"
        "# Exploratory legacy teacher/split only; not patient-safe confirmation.\n"
        "# Full training NOT launched. Preserve parent TLS/SWA/optimizer.\n"
    )
    predicted = f"{PREFIX}_predicted_split0"
    predicted_path = f"configs/h7/v23/{predicted}.yaml"
    docs[predicted_path] = {
        "inherits": f"configs/h7/v17/{PARENT}.yaml",
        "cfg": {
            "experiment": {
                "id": predicted,
                "tags": ["v23", "event_features", "legacy_exploratory"],
            },
            "data": {
                "division_score_path": "data/derived/division_score_F0.csv",
                "division_score_strict": True,
            },
            "model": {
                "type": "event_conditioned",
                "event_conditioning": {
                    "hidden": 32,
                    "enabled": True,
                    "mode": "predicted",
                    "neutral_score": 0.5,
                    "scale": 1.0,
                },
            },
        },
    }
    for mode, override in (("constant", {"mode": "constant"}), ("disabled", {"enabled": False})):
        run_id = f"{PREFIX}_{mode}_split0"
        docs[f"configs/h7/v23/{run_id}.yaml"] = {
            "inherits": predicted_path,
            "cfg": {
                "experiment": {"id": run_id, "tags": ["v23", mode, "legacy_exploratory"]},
                "model": {"event_conditioning": override},
            },
        }
    for seed in range(3):
        docs[f"configs/h7/v23/event_audit_parent_seed{seed}.yaml"] = {
            "inherits": f"configs/h7/v17/{PARENT}.yaml",
            "builder": "event_signal_audit",
            "cfg": {
                "experiment": {
                    "id": f"v23_event_audit_parent_seed{seed}",
                    "out_root": "runs/event_audit",
                },
                "event_audit": {
                    "source_run": f"runs/h7/{PARENT}_seed{seed}",
                    "score_path": "data/derived/division_score_F0.csv",
                    "weights": [0.25, 0.5, 1.0],
                    "radius": 2,
                    "floor": 0.0001,
                    "clock_bin_hours": 2.0,
                    "clock_prior_strength": 10.0,
                    "allow_legacy_overlap": True,
                },
            },
        }
    for seed in range(3):
        docs[f"configs/h7/v23/event_audit_onset_parent_seed{seed}.yaml"] = {
            "inherits": f"configs/h7/v23/event_audit_parent_seed{seed}.yaml",
            "cfg": {
                "experiment": {"id": f"v23_event_audit_onset_parent_seed{seed}"},
                "event_audit": {"include_onset_oracle": True},
            },
        }
    docs["configs/h7/v23/sweep_training_NOT_LAUNCHED.yaml"] = {
        "experiments": [
            {"config": f"configs/h7/v23/{PREFIX}_{mode}_split0.yaml", "seed": seed}
            for mode in ("disabled", "constant", "predicted")
            for seed in range(3)
        ]
    }
    docs["configs/h7/v23/sweep_validation_audit.yaml"] = {
        "experiments": [f"configs/h7/v23/event_audit_parent_seed{seed}.yaml" for seed in range(3)]
    }
    return {path: header + yaml.safe_dump(doc, sort_keys=False) for path, doc in docs.items()}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--emit-json", action="store_true", help="print rendered files without writing"
    )
    args = parser.parse_args()
    docs = render_configs()
    if args.emit_json:
        print(json.dumps(docs))
        return
    for path, expected in docs.items():
        file = ROOT / path
        if not file.exists() or file.read_text() != expected:
            raise SystemExit(f"missing/stale generated config: {path}")
    print(f"OK: {len(docs)} generated v23 YAML files match; no files changed")


if __name__ == "__main__":
    main()
