#!/usr/bin/env python3
"""v36: what did the defective *training* videos cost?

Every committed model was trained on the released labels, defective videos included. Re-scoring
without the defective *test* videos (scripts/noise_impact.py) cannot say what the ~6 % defective
*training* videos did. This family retrains on ``nantes_grouped_v2_trainclean_v1``: train minus the
29 inspected defective videos, with val and test byte-identical to ``nantes_grouped_v2``, so every run is
paired video for video with the committed run of the same recipe and seed.

* **Probe (per-frame ResNet-18).** It has no temporal head that could smooth over a bad label, so it
  shows the effect most directly. It has no committed v2 run, so both arms are run here.
* **Paper recipes.** Reference LSTM and cross-focal transformer. The noisy arm is the committed v35
  family B; only the clean arm is new. Each config inherits the v35 config and changes data.split only.

    PYTHONPATH=src python scripts/make_v36_configs.py
"""
from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "configs/h7/v36"
V2 = "data/splits/nantes_grouped_v2.json"
CLEAN = "data/splits/nantes_grouped_v2_trainclean_v1.json"
SEEDS = (0, 1, 2)


def _dump(path: Path, doc: dict, header: str) -> None:
    path.write_text(f"# v36: {header}\n# Generated by scripts/make_v36_configs.py -- do not edit by hand.\n"
                    + yaml.safe_dump(doc, sort_keys=False))


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    names = []
    # per-frame probe, both arms; recipe = the sibling-leak / image-split per-frame recipe
    for arm, split in (("noisy", V2), ("trainclean", CLEAN)):
        eid = "resnet18_none_grouped_v2" + ("" if arm == "noisy" else "_trainclean")
        _dump(OUT / f"{eid}.yaml", {"inherits": "configs/h7/siblingleak/_base.yaml", "cfg": {
            "experiment": {"id": eid, "out_root": "runs/h7", "tags": ["v36", "label_noise", arm, "per_frame"],
                           "notes": f"per-frame ResNet-18 on nantes_grouped_v2, {arm} train"},
            "data": {"split": split},
            "model": {"backbone": {"name": "resnet18", "pretrained": True}},
        }}, f"{eid} -- per-frame probe, {arm} training set")
        names.append(eid)
    for src in ("resnet18_lstm_L4_grouped_v2", "resnet18_transformer_L16_crossfocal7_evalfix_grouped_v2"):
        eid = f"{src}_trainclean"
        _dump(OUT / f"{eid}.yaml", {"inherits": f"configs/h7/v35/{src}.yaml", "cfg": {
            "experiment": {"id": eid, "tags": ["v36", "label_noise", "trainclean"],
                           "notes": f"recipe inherited verbatim from {src}; only data.split differs"},
            "data": {"split": CLEAN},
        }}, f"{eid} -- {src} with the defective videos removed from train")
        names.append(eid)
    frame_n, frame_c, lstm, cf = names
    # two queues of ~equal length (cross-focal ~3 h/seed, LSTM ~1 h, per-frame ~20 min)
    queues = {
        "sweep_gpu0": [(frame_n, s) for s in SEEDS] + [(frame_c, s) for s in SEEDS] + [(lstm, s) for s in SEEDS] + [(cf, 2)],
        "sweep_gpu1": [(cf, 0), (cf, 1)],
    }
    for q, runs in queues.items():
        (OUT / f"{q}.yaml").write_text(yaml.safe_dump(
            {"experiments": [{"config": f"configs/h7/v36/{n}.yaml", "seed": s} for n, s in runs]}, sort_keys=False))
    print(f"wrote {len(names)} configs + {len(queues)} sweeps -> {OUT}")


if __name__ == "__main__":
    main()
