#!/usr/bin/env python3
"""Configs for the out-of-fold timeline audit: the v36 per-frame ResNet-18 recipe on each of
the five couple-grouped audit folds; only data.split differs.

    PYTHONPATH=src python scripts/make_oof_audit_configs.py
"""
from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "configs/h7/oof_audit"


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for k in range(5):
        eid = f"resnet18_none_oof_audit_k{k}"
        doc = {"inherits": "configs/h7/v36/resnet18_none_grouped_v2.yaml", "cfg": {
            "experiment": {"id": eid, "tags": ["oof_audit", "timeline_audit"],
                           "notes": "per-frame classifier for the out-of-fold timeline audit; only data.split differs"},
            "data": {"split": f"data/splits/nantes_oof_audit_v1_k{k}.json"}}}
        (OUT / f"{eid}.yaml").write_text(f"# out-of-fold timeline audit, fold {k}.\n"
                                         "# Generated by scripts/make_oof_audit_configs.py -- do not edit by hand.\n"
                                         + yaml.safe_dump(doc, sort_keys=False))
    for q, ks in (("sweep_gpu0", (0, 1, 2)), ("sweep_gpu1", (3, 4))):
        (OUT / f"{q}.yaml").write_text(yaml.safe_dump(
            {"experiments": [{"config": f"configs/h7/oof_audit/resnet18_none_oof_audit_k{k}.yaml", "seed": 0} for k in ks]},
            sort_keys=False))
    print(f"wrote 5 configs + 2 sweeps -> {OUT}")


if __name__ == "__main__":
    main()
