#!/usr/bin/env python
"""Generate the v29 milestone-query configs.

Three one-change arms x three matched source/training seeds on the frozen v26 caches:
onset_linear (no global queries) -> query_global (+ learned milestone queries) -> query_refine (+ local refinement).
The SCE encoder, its framewise head/objective and the v27 SCE optimiser recipe are shared by every arm, so the
matched parent is the already-completed v27 ``sce`` run of the same seed.

  python scripts/make_v29_configs.py
"""
from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "configs/h7/v29"
ARMS = {
    "onset_linear": "control: per-frame linear onset head, no global milestone queries",
    "query_global": "treatment 1: learned milestone queries decoded against the whole video",
    "query_refine": "treatment 2 (primary): milestone queries plus local refinement around each coarse onset",
}

BASE = {
    "inherits": "configs/h7/v26/_base.yaml",
    "builder": "cached_video_validation_training",
    "cfg": {
        "experiment": {
            "id": "v29_base_do_not_run",
            "out_root": "runs/h7/v29",
            "tags": ["v29", "milestone-query", "patient-grouped", "trainval-only"],
            "notes": "SCE encoder + milestone onset localisation on frozen v26 visual features",
        },
        "data": {"input_mode": "visual", "sequence_mode": "full"},
        "model": {
            "type": "milestone_query_adapter",
            "backbone": {"name": "cached_features"},
            "head": {"name": "none"},
            "milestone": {
                "variant": "query_refine",
                "hidden": 96, "layers": 6, "intermediate_layers": [2, 4, 6], "attention_reduction": 2, "dropout": 0.5,
                "query_dim": 128, "query_layers": 2, "query_heads": 4, "query_dropout": 0.1,
                "local_kernel": 5, "refine_radius": 8, "combine_weight": 1.0,
            },
            "num_classes": 16,
            "dropout": 0.5,
        },
        "loss": {
            "name": "milestone_objective",
            "semantic_weight": 0.8, "smooth_weight": 0.3, "milestone_weight": 1.0, "combined_weight": 0.8,
            "truncation": 4.0, "target_sigma": 1.0,
        },
        "optimizer": {"name": "adamw", "lr": 0.0001, "weight_decay": 0.01},
        "scheduler": {"name": "cosine", "eta_min": 0.0},
        "training": {
            "epochs": 100, "batch_size": 1, "eval_len": 1024, "eval_stride": 1024, "eval_batch_size": 1024,
            "num_workers": 0, "amp": True, "monitor": "p_t", "grad_accum": 8, "swa_last": 0,
        },
    },
}


def _dump(path: Path, doc: dict, header: str) -> None:
    path.write_text(f"# {header}\n# Generated by scripts/make_v29_configs.py -- do not edit by hand.\n"
                    + yaml.safe_dump(doc, sort_keys=False))


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    _dump(OUT / "_base.yaml", BASE, "v29 milestone queries + local refinement: shared SCE recipe, validation only")
    sweeps: dict[str, list] = {"gpu0": [], "gpu1": []}
    order = [(arm, src) for src in (0, 1, 2) for arm in ARMS]
    for i, (arm, src) in enumerate(order):
        name = f"{arm}_src{src}"
        doc = {
            "inherits": "configs/h7/v29/_base.yaml",
            "cfg": {
                "experiment": {"id": f"v29_{name}", "seed": src,
                               "tags": ["v29", arm, f"matched-source-seed-{src}", "trainval-only"],
                               "notes": ARMS[arm]},
                "data": {"feature_cache": f"runs/h7/v26/features_seed{src}"},
                "model": {"milestone": {"variant": arm}},
            },
        }
        _dump(OUT / f"{name}.yaml", doc, f"v29 {arm}, matched source seed {src}. {ARMS[arm]}")
        sweeps["gpu0" if i % 2 == 0 else "gpu1"].append({"config": f"configs/h7/v29/{name}.yaml", "seed": src})
    for gpu, runs in sweeps.items():
        (OUT / f"sweep_{gpu}.yaml").write_text(yaml.safe_dump({"experiments": runs}, sort_keys=False))
    print(f"wrote {len(order)} run configs + base + 2 sweeps -> {OUT}")


if __name__ == "__main__":
    main()
