#!/usr/bin/env python3
"""v40: the per-frame classifier under the transformer's optimiser.

v39 showed that the reference -> transformer step on the five folds is the optimiser (SGD -> AdamW, +0.041), not the
head. The per-frame classifier has only ever been trained with SGD, so the margin of the temporal models over it mixes
temporal context with optimisation. Two arms, all five folds, three seeds:
  ``resnet18_none_adamw_split{k}``  the per-frame classifier with AdamW lr 1e-4, wd 0.05, warm-up cosine (the
                                    transformer's recipe; batch, epochs, data unchanged)
  ``resnet18_none_split{k}``        seeds 1 and 2 on folds 1-4, so the SGD arm has three seeds everywhere (configs
                                    unchanged: configs/h7/v4, configs/h7/resnet18_none_split0.yaml)
Matched contrasts then answer: does AdamW lift a per-frame model as much as an LSTM (+0.041)? and what does temporal
context add at a matched recipe (AdamW LSTM / transformer - AdamW per-frame)?

    PYTHONPATH=src python scripts/make_v40_configs.py     # -> configs/h7/v40/{*.yaml, sweep_lane{a,b}.yaml}
"""
from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "configs/h7/v40"
SEEDS = (0, 1, 2)
ADAMW = {"optimizer": {"name": "adamw", "lr": 0.0001, "weight_decay": 0.05},
         "scheduler": {"name": "warmup_cosine", "warmup_epochs": 1}}


def src(k: int) -> str:
    return "configs/h7/resnet18_none_split0.yaml" if k == 0 else f"configs/h7/v4/resnet18_none_split{k}.yaml"


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    runs = []
    for k in range(5):
        eid = f"resnet18_none_adamw_split{k}"
        doc = {"inherits": src(k), "cfg": {"experiment": {"id": eid, "tags": ["v40"], "notes": "per-frame classifier, transformer's AdamW recipe"}, **ADAMW}}
        p = OUT / f"{eid}.yaml"
        p.write_text(f"# v40: {eid}\n# Generated by scripts/make_v40_configs.py -- do not edit by hand.\n" + yaml.safe_dump(doc, sort_keys=False))
        runs += [(str(p.relative_to(ROOT)), s) for s in SEEDS]
        if k > 0:
            runs += [(src(k), s) for s in (1, 2)]
    lanes = {"sweep_lanea": runs[0::2], "sweep_laneb": runs[1::2]}
    for name, r in lanes.items():
        (OUT / f"{name}.yaml").write_text(yaml.safe_dump({"experiments": [{"config": c, "seed": s} for c, s in r]}, sort_keys=False))
    print(f"{len(runs)} runs in {len(lanes)} lanes")


if __name__ == "__main__":
    main()
