#!/usr/bin/env python
"""Generate the v33 end-to-end whole-video configs.

Two arms x three matched seeds on the raw frames of the frozen patient-grouped split (data identity inherited from
the v25 baseline): ``e2e`` (cross-focal backbone trainable, backbone lr x0.1) and ``frozen_control`` (identical
schedule, backbone frozen -- must reproduce v27 SCE). Both warm-start the backbone from the seed-matched v25
``swa.pt`` and the SCE head from the seed-matched v27 ``sce`` checkpoint, and standardise features with the
seed-matched v26 cache statistics. The only key that differs between the arms is ``model.e2e.freeze_backbone``.

  python scripts/make_v33_configs.py
"""
from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "configs/h7/v33"
ARMS = {"frozen_control": True, "e2e": False}


def _dump(path: Path, doc: dict, header: str) -> None:
    path.write_text(f"# {header}\n# Generated by scripts/make_v33_configs.py -- do not edit by hand.\n"
                    + yaml.safe_dump(doc, sort_keys=False))


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    base = {
        "inherits": "configs/h7/v25_grouped_recipe_baseline.yaml",
        "builder": "kinetic_validation_training",
        "cfg": {
            "experiment": {"id": "v33_base_do_not_run", "out_root": "runs/h7/v33",
                           "tags": ["v33", "end-to-end", "patient-grouped", "trainval-only"],
                           "notes": "whole-video training with a trainable cross-focal backbone + warm-started SCE head"},
            "data": {"dataset": "nantes_video_trainval"},
            "model": {
                "type": "e2e_sce",
                "backbone": {"name": "crossfocal", "cnn": "resnet18", "pretrained": True, "nhead": 4},
                "head": {"name": "none"},
                "e2e": {"hidden": 96, "layers": 6, "intermediate_layers": [2, 4, 6], "attention_reduction": 2,
                        "dropout": 0.5, "chunk": 64, "freeze_backbone": False},
                "num_classes": 16,
                "dropout": 0.5,
            },
            "loss": {"name": "embryodiff_objective", "semantic_weight": 0.8, "smooth_weight": 0.3,
                     "boundary_weight": 0.0, "diffusion_weight": 0.0, "truncation": 4.0},
            "optimizer": {"name": "adamw", "lr": 0.0001, "weight_decay": 0.01, "backbone_lr_mult": 0.1},
            "scheduler": {"name": "cosine", "eta_min": 0.0},
            "training": {"epochs": 30, "batch_size": 1, "eval_len": 1024, "eval_stride": 1024, "eval_batch_size": 1024,
                         "num_workers": 12, "amp": True, "monitor": "p_t", "grad_accum": 8, "swa_last": 0},
        },
    }
    _dump(OUT / "_base.yaml", base, "v33 end-to-end whole-video: v25 raw-frame data identity, SCE objective, validation only")
    runs = []
    for k in (0, 1, 2):
        for arm, frozen in ARMS.items():
            name = f"{arm}_src{k}"
            doc = {"inherits": "configs/h7/v33/_base.yaml", "cfg": {
                "experiment": {"id": f"v33_{name}", "seed": k,
                               "tags": ["v33", arm, f"matched-source-seed-{k}", "trainval-only"],
                               "notes": "backbone frozen: pipeline check, must reproduce v27 SCE" if frozen
                               else "backbone trainable with a whole-video objective (the one change)"},
                "model": {"e2e": {
                    "freeze_backbone": frozen,
                    "init_backbone_from": f"runs/h7/v25/v25_grouped_recipe_baseline_seed{k}/swa.pt",
                    "init_head_from": f"runs/h7/v27/v27_sce_src{k}_seed{k}/best.pt",
                    "feature_stats_cache": f"runs/h7/v26/features_seed{k}",
                }},
            }}
            _dump(OUT / f"{name}.yaml", doc, f"v33 {arm}, matched seed {k}.")
            runs.append({"config": f"configs/h7/v33/{name}.yaml", "seed": k})
    (OUT / "sweep_all.yaml").write_text(yaml.safe_dump({"experiments": runs}, sort_keys=False))
    print(f"wrote {len(runs)} run configs + base + sweep -> {OUT}")


if __name__ == "__main__":
    main()
