#!/usr/bin/env python3
"""Configs for the sibling-leakage difference-in-differences experiment (CLEAVE defect 3).

Two arms x three seeds on the paired splits written by ``scripts/make_sibling_leak_split.py``.  The
recipe is byte-identical to the image-level-split ablation already reported in the paper
(``runs/h7/resnet18_none_imagesplit_seed0``): a per-frame classifier with no temporal head, so the
evaluation-window defect of Section 1 cannot interact with the measurement.  The only key that
differs between the arms is ``data.split``.

    PYTHONPATH=src python scripts/make_siblingleak_configs.py
"""
from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "configs/h7/siblingleak"
ARMS = ("clean", "leaky")
BACKBONES = {"resnet18": dict(batch_size=40), "efficientnet_v2_l": dict(batch_size=16)}
SEEDS = (0, 1, 2)


def _dump(path: Path, doc: dict, header: str) -> None:
    path.write_text(f"# {header}\n# Generated by scripts/make_siblingleak_configs.py -- do not edit by hand.\n"
                    + yaml.safe_dump(doc, sort_keys=False))


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    base = {
        "inherits": "configs/h7/_base.yaml",
        "builder": "kinetic_training",
        "cfg": {
            "experiment": {"id": "siblingleak_base_do_not_run", "out_root": "runs/h7/siblingleak",
                           "tags": ["siblingleak", "did", "leakage_demo"],
                           "notes": "per-frame classifier; arms differ only in data.split"},
            "data": {"dataset": "nantes_frames", "split_mode": "video"},
            "model": {"head": {"name": "none"}},
            "training": {"epochs": 10, "batch_size": 40, "monitor": "p_v"},
        },
    }
    _dump(OUT / "_base.yaml", base, "sibling-leakage DiD: per-frame recipe of the image-split ablation")

    runs = []
    for bk, over in BACKBONES.items():
        for arm in ARMS:
            for seed in SEEDS:
                name = f"siblingleak_{arm}_{bk}_seed{seed}"
                doc = {"inherits": "configs/h7/siblingleak/_base.yaml", "cfg": {
                    "experiment": {"id": f"siblingleak_{arm}_{bk}", "seed": seed,
                                   "tags": ["siblingleak", arm, bk],
                                   "notes": f"{arm} arm: {'41 test embryos have a sibling in train' if arm == 'leaky' else 'no test embryo has a sibling in train'}"},
                    "data": {"split": f"data/splits/nantes_siblingleak_{arm}_v1.json"},
                    "model": {"backbone": {"name": bk, "pretrained": True}},
                    "training": dict(over),
                }}
                _dump(OUT / f"{name}.yaml", doc, f"sibling-leak DiD, {arm} arm, {bk}, seed {seed}.")
                runs.append({"config": f"configs/h7/siblingleak/{name}.yaml", "seed": seed})
    primary = [r for r in runs if "resnet18" in r["config"]]
    (OUT / "sweep_resnet18.yaml").write_text(yaml.safe_dump({"experiments": primary}, sort_keys=False))
    (OUT / "sweep_all.yaml").write_text(yaml.safe_dump({"experiments": runs}, sort_keys=False))
    print(f"wrote {len(runs)} run configs ({len(primary)} primary resnet18) + base + sweeps -> {OUT}")


if __name__ == "__main__":
    main()
