#!/usr/bin/env python3
"""v35: the three experiment families Paper 1 still needs.

**A -- attribution controls, seeds 1 and 2.** The abstract attributes the cross-focal gain to the
temporal head and to using the planes rather than to the fusion. That rests on the 3-plane stacked
control matching the cross-focal model, but the control has one seed per fold against the
cross-focal model's three. Family A adds seeds 1 and 2 to the 3-plane control on all five folds and
to the 1-plane control on folds 1-4 (fold 0 already has three). No new config files are needed:
the existing per-fold configs are re-run under new seeds and land in ``<id>_seed{1,2}``.

**B -- the recommended split is used.** ``nantes_grouped_v2`` (couple-level grouping, zero leaks) is
released as the CLEAVE split but nothing has been evaluated on it. The reference LSTM and the
cross-focal transformer are run on it with three seeds, so the corrected protocol carries the same
comparison it carries on v1.

**C -- the protocol table's missing rows.** Three released baselines have no patient-grouped cells:
R(2+1)D-18, ResNet-50-LSTM and the 1-plane corrected-window transformer. Three seeds each.

Families B and C inherit the committed config of the same recipe and change ``data.split`` only, so
the recipe cannot drift from the released-protocol row it is compared against.

    PYTHONPATH=src python scripts/make_v35_configs.py
"""
from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "configs/h7/v35"
GROUPED_V1 = "data/splits/nantes_grouped_v1.json"
GROUPED_V2 = "data/splits/nantes_grouped_v2.json"

#: family A: (existing config id, folds, seeds to add)
FAMILY_A = [
    ("resnet18_transformer_L16_multifocal3_evalfix_split{k}", (0, 1, 2, 3, 4), (1, 2)),
    ("resnet18_transformer_L16_evalfix_split{k}", (1, 2, 3, 4), (1, 2)),
]
#: family B/C: (source config id, new id, split file)
#: Per-run training overrides. NEGATIVE RESULT, kept so the diagnosis is not repeated: R(2+1)D runs
#: at ~20.6 min/epoch against ~5 min for the other recipes, and sampling showed the GPU at 0 % between
#: spikes, so worker count was raised from 8 to 24 on the assumption that the loader was starving it.
#: It was not. The first 24-worker epoch took 22.7 min, slightly *slower*, and a second look at the
#: host found CPU 95 % idle, iowait 0 % and load average 6.5 on 88 cores, so neither CPU nor disk was
#: saturated. The cost is per-clip read latency (eight JPEGs at random offsets per clip, no pre-resized
#: cache, unlike every other recipe), which more workers do not reduce. The real fix would be to build
#: this recipe a cache the way scripts/build_nantes_cache.py does for the others; that changes the data
#: path and would break comparability with the committed fold-0 runs, so it is not done here.
OVERRIDES = {"r2plus1d_L8_grouped_v1": {"training": {"num_workers": 24}}}

DERIVED = [
    ("resnet18_lstm_L4_grouped_v1", "resnet18_lstm_L4_grouped_v2", GROUPED_V2),
    ("resnet18_transformer_L16_crossfocal7_evalfix_grouped_v1",
     "resnet18_transformer_L16_crossfocal7_evalfix_grouped_v2", GROUPED_V2),
    ("r2plus1d_L8_split0", "r2plus1d_L8_grouped_v1", GROUPED_V1),
    ("resnet50_lstm_L8_split0", "resnet50_lstm_L8_grouped_v1", GROUPED_V1),
    ("resnet18_transformer_L16_evalfix_split0", "resnet18_transformer_L16_evalfix_grouped_v1", GROUPED_V1),
]
SEEDS = (0, 1, 2)


def find_config(exp_id: str) -> Path:
    hits = sorted((ROOT / "configs/h7").rglob(f"{exp_id}.yaml"))
    if not hits:
        raise SystemExit(f"no committed config for {exp_id}")
    return hits[0]


def rel(p: Path) -> str:
    return str(p.relative_to(ROOT))


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.glob("*.yaml"):
        old.unlink()

    a_runs, b_runs, c_runs = [], [], []
    for template, folds, seeds in FAMILY_A:
        for k in folds:
            cfg = rel(find_config(template.format(k=k)))
            a_runs += [{"config": cfg, "seed": s} for s in seeds]

    for src_id, new_id, split in DERIVED:
        src = yaml.safe_load(find_config(src_id).read_text())
        doc = {
            "inherits": rel(find_config(src_id)),
            "cfg": {
                "experiment": {"id": new_id,
                               "tags": sorted(set(src.get("cfg", {}).get("experiment", {}).get("tags", []))
                                              | {"v35", "patient_grouped"}),
                               "notes": f"recipe inherited verbatim from {src_id}; only data.split differs"},
                "data": {"split": split},
                **OVERRIDES.get(new_id, {}),
            },
        }
        path = OUT / f"{new_id}.yaml"
        path.write_text(f"# v35: {new_id} -- {src_id} on {Path(split).stem}. "
                        "Generated by scripts/make_v35_configs.py -- do not edit by hand.\n"
                        + yaml.safe_dump(doc, sort_keys=False))
        target = b_runs if split == GROUPED_V2 else c_runs
        target += [{"config": rel(path), "seed": s} for s in SEEDS]

    # family C is split by cost: R(2+1)D-18 is ~5.5 h per run against ~1 h for the other two, so it
    # goes to whichever GPU frees first instead of serialising behind family B.
    c1 = [r for r in c_runs if "r2plus1d" in r["config"]]
    c2 = [r for r in c_runs if "r2plus1d" not in r["config"]]
    for name, runs, note in (("sweep_a_attribution", a_runs, "attribution controls, seeds 1-2"),
                             ("sweep_b_grouped_v2", b_runs, "reference + cross-focal on nantes_grouped_v2"),
                             ("sweep_c_baselines_grouped", c_runs, "three released baselines on nantes_grouped_v1"),
                             ("sweep_c1_r2plus1d", c1, "family C, the expensive baseline alone"),
                             ("sweep_c2_cheap", c2, "family C, the two cheap baselines")):
        (OUT / f"{name}.yaml").write_text(f"# v35 {note}\n" + yaml.safe_dump({"experiments": runs}, sort_keys=False))
    (OUT / "sweep_all.yaml").write_text("# v35, run order A -> B -> C\n"
                                        + yaml.safe_dump({"experiments": a_runs + b_runs + c_runs}, sort_keys=False))
    print(f"A attribution: {len(a_runs)} runs | B grouped_v2: {len(b_runs)} | C baselines: {len(c_runs)} "
          f"| total {len(a_runs) + len(b_runs) + len(c_runs)} -> {OUT}")


if __name__ == "__main__":
    main()
