#!/usr/bin/env python3
"""v39: the controls Paper 1 still lacks. Every config inherits a committed config and
changes only the keys named here.

**D -- attribution of the head step.** The reference -> single-plane transformer step changes four things at once:
clip length (4 -> 16), evaluation window (150-chunk -> 16/8), optimiser (SGD -> AdamW + warm-up cosine + wd 0.05) and
head (LSTM -> transformer). Two intermediate LSTM arms on all five folds, three seeds, split the step:
  D1 ``resnet18_lstm_L16_win``        clip 16, batch 4 and the corrected window, released SGD optimiser
  D2 ``resnet18_lstm_L16_win_adamw``  D1 + the transformer's optimiser and schedule (AdamW, warm-up cosine, wd 0.05)
so that reference -> D1 is clip+batch+window, D1 -> D2 the optimiser, D2 -> transformer the head (D2 and the
transformer differ in nothing else).

**P -- plane-matched fusion control on all folds.** Seven planes stacked as channels into the same transformer
(``resnet18_transformer_L16_multifocal7_evalfix``) has three fold-0 seeds only; folds 1-4 x 3 seeds are added, so
cross-focal attention vs channel stacking is compared at equal plane count on every fold.

**C -- the ceiling off the selection fold.** Five common-recipe configurations spanning the head families are run
on the recommended couple-level split (nantes_grouped_v2), three seeds each, data.split only changed.

    PYTHONPATH=src python scripts/make_v39_configs.py
"""
from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "configs/h7/v39"
SEEDS = (0, 1, 2)
FOLD = "data/splits/nantes_official/split{k}.csv"
V2 = "data/splits/nantes_grouped_v2.json"
ADAMW = {"optimizer": {"name": "adamw", "lr": 0.0001, "weight_decay": 0.05},
         "scheduler": {"name": "warmup_cosine", "warmup_epochs": 1}}
WIN = {"training": {"batch_size": 4, "eval_len": 16, "eval_stride": 8}}
#: (source config, new id, extra cfg) for family C
CEILING = [("configs/h7/v3/resnet18_transformer_L16_evalfix_split0.yaml", "resnet18_transformer_L16_evalfix_grouped_v2"),
           ("configs/h7/resnet50_lstm_L8_split0.yaml", "resnet50_lstm_L8_grouped_v2"),
           ("configs/h7/resnet18_tcn_L16_split0.yaml", "resnet18_tcn_L16_grouped_v2"),
           ("configs/h7/resnet18_gru_L8_split0.yaml", "resnet18_gru_L8_grouped_v2"),
           ("configs/h7/v5/resnet18_mamba_L16_split0.yaml", "resnet18_mamba_L16_grouped_v2")]
MINUTES = {"lstm_L16_win": 45, "multifocal7": 80, "grouped_v2": 55}


def merge(*ds: dict) -> dict:
    out: dict = {}
    for d in ds:
        for k, v in d.items():
            out[k] = merge(out.get(k, {}), v) if isinstance(v, dict) else v
    return out


def dump(eid: str, inherits: str, cfg: dict, note: str) -> str:
    doc = {"inherits": inherits, "cfg": merge({"experiment": {"id": eid, "tags": ["v39"], "notes": note}}, cfg)}
    p = OUT / f"{eid}.yaml"
    p.write_text(f"# v39: {eid}\n# Generated by scripts/make_v39_configs.py -- do not edit by hand.\n"
                 + yaml.safe_dump(doc, sort_keys=False))
    return str(p.relative_to(ROOT))


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    runs: list[tuple[str, int, int]] = []
    for k in range(5):
        base = "configs/h7/resnet18_lstm_L16_split0.yaml"
        d1 = dump(f"resnet18_lstm_L16_win_split{k}", base, merge({"data": {"split": FOLD.format(k=k)}}, WIN),
                  "D1: LSTM, clip 16, corrected window, released SGD recipe")
        d2 = dump(f"resnet18_lstm_L16_win_adamw_split{k}", base, merge({"data": {"split": FOLD.format(k=k)}}, WIN, ADAMW),
                  "D2: D1 + the transformer's AdamW / warm-up cosine / wd 0.05")
        runs += [(d1, s, MINUTES["lstm_L16_win"]) for s in SEEDS] + [(d2, s, MINUTES["lstm_L16_win"]) for s in SEEDS]
    for k in range(1, 5):
        p = dump(f"resnet18_transformer_L16_multifocal7_evalfix_split{k}",
                 "configs/h7/v16/resnet18_transformer_L16_multifocal7_evalfix_split0.yaml",
                 {"data": {"split": FOLD.format(k=k)}}, "P: seven planes stacked, plane-matched control of cross-focal")
        runs += [(p, s, MINUTES["multifocal7"]) for s in SEEDS]
    for src, eid in CEILING:
        p = dump(eid, src, {"data": {"split": V2}}, f"C: {Path(src).stem} on the recommended split; data.split only")
        runs += [(p, s, MINUTES["grouped_v2"]) for s in SEEDS]
    queues: dict[str, list] = {"sweep_gpu0": [], "sweep_gpu1": []}
    load = {q: 0 for q in queues}
    for cfg, seed, m in sorted(runs, key=lambda r: -r[2]):
        q = min(load, key=load.get)
        queues[q].append({"config": cfg, "seed": seed})
        load[q] += m
    for q, r in queues.items():
        (OUT / f"{q}.yaml").write_text(yaml.safe_dump({"experiments": r}, sort_keys=False))
    print(f"{len(runs)} runs; estimated GPU minutes per queue {load}")


if __name__ == "__main__":
    main()
