#!/usr/bin/env python
"""Generate the v31 configs: the event-shaped onset head as the registered treatment.

Base = v29 ``onset_linear`` (the best-scoring v29 arm), three one-change arms x three matched source seeds:
``combined_smooth`` (SCE smoothing also on the combined output), ``gated_fusion`` (learned per-frame trust in the
milestone evidence) and ``duration_hazard`` (onsets parameterised as time-varying hazards, monotone by
construction). Parent for the gate is v27 ``sce``; v29 ``onset_linear`` is the treatment baseline.

  python scripts/make_v31_configs.py
"""
from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "configs/h7/v31"
ARMS = {
    "combined_smooth": ({"loss": {"combined_smooth_weight": 0.3}},
                        "onset_linear + SCE truncated smoothing applied to the combined output"),
    "gated_fusion": ({"model": {"milestone": {"fusion": "gated"}}},
                     "onset_linear + learned per-frame gate on the milestone evidence (product of experts otherwise)"),
    "duration_hazard": ({"model": {"milestone": {"parameterisation": "hazard"}}},
                        "onset_linear with onsets parameterised as per-frame hazards: ordered CDFs by construction"),
}


def _dump(path: Path, doc: dict, header: str) -> None:
    path.write_text(f"# {header}\n# Generated by scripts/make_v31_configs.py -- do not edit by hand.\n"
                    + yaml.safe_dump(doc, sort_keys=False))


def _merge(a: dict, b: dict) -> dict:
    out = dict(a)
    for k, v in b.items():
        out[k] = _merge(out[k], v) if isinstance(v, dict) and isinstance(out.get(k), dict) else v
    return out


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    base = {
        "inherits": "configs/h7/v29/_base.yaml",
        "cfg": {
            "experiment": {"id": "v31_base_do_not_run", "out_root": "runs/h7/v31",
                           "tags": ["v31", "onset-head", "patient-grouped", "trainval-only"],
                           "notes": "v29 onset_linear as the registered treatment; one change per arm"},
            "model": {"milestone": {"variant": "onset_linear"}},
        },
    }
    _dump(OUT / "_base.yaml", base, "v31 event-shaped onset head: v29 onset_linear base, validation only")
    sweeps: dict[str, list] = {"gpu0": [], "gpu1": []}
    order = [(arm, src) for src in (0, 1, 2) for arm in ARMS]
    for i, (arm, src) in enumerate(order):
        change, note = ARMS[arm]
        name = f"{arm}_src{src}"
        cfg = _merge({
            "experiment": {"id": f"v31_{name}", "seed": src,
                           "tags": ["v31", arm, f"matched-source-seed-{src}", "trainval-only"], "notes": note},
            "data": {"feature_cache": f"runs/h7/v26/features_seed{src}"},
        }, change)
        _dump(OUT / f"{name}.yaml", {"inherits": "configs/h7/v31/_base.yaml", "cfg": cfg},
              f"v31 {arm}, matched source seed {src}. {note}")
        sweeps["gpu0" if i % 2 == 0 else "gpu1"].append({"config": f"configs/h7/v31/{name}.yaml", "seed": src})
    for gpu, runs in sweeps.items():
        (OUT / f"sweep_{gpu}.yaml").write_text(yaml.safe_dump({"experiments": runs}, sort_keys=False))
    allruns = sorted(sweeps["gpu0"] + sweeps["gpu1"], key=lambda e: (e["seed"], e["config"]))
    (OUT / "sweep_all.yaml").write_text(yaml.safe_dump({"experiments": allruns}, sort_keys=False))
    print(f"wrote {len(order)} run configs + base + sweeps -> {OUT}")


if __name__ == "__main__":
    main()
