#!/usr/bin/env python3
"""v38: the label-noise retraining on defect log v3.

v37 (below, kept for the record) was stopped: its split came from an in-sample timeline audit that could not see
mismatches among its classifier's own training videos. v38 is v37 with defect log v3 (out-of-fold audit).

Original v37 description:

v36 removed the 41 inspected videos of defect log v1 from training. Round-4 review and the image--annotation timeline
audit replaced that list: defect log v2 removes only tier A (labels that are not about the image: 14 training videos,
most of them timeline mismatches v1 had missed or mislabelled), keeps image artefacts and atypical biology, and cuts
the extended labels of embryos removed from the well (data.train_label_cutoff, training partition only). Val and test
are identical to nantes_grouped_v2, so every run pairs with the committed run of the same recipe and seed.

    PYTHONPATH=src python scripts/make_v38_configs.py
"""
from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "configs/h7/v38"
SPLIT = "data/splits/nantes_grouped_v2_trainclean_v3.json"
CUTOFF = "data/qc/nantes_label_cutoff_v3.json"
SOURCES = {"resnet18_none_grouped_v2": "configs/h7/v36/resnet18_none_grouped_v2.yaml",
           "resnet18_lstm_L4_grouped_v2": "configs/h7/v35/resnet18_lstm_L4_grouped_v2.yaml",
           "resnet18_transformer_L16_crossfocal7_evalfix_grouped_v2": "configs/h7/v35/resnet18_transformer_L16_crossfocal7_evalfix_grouped_v2.yaml"}
SEEDS = (0, 1, 2)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    ids = []
    for src, cfg in SOURCES.items():
        eid = f"{src}_trainclean3"
        doc = {"inherits": cfg, "cfg": {
            "experiment": {"id": eid, "tags": ["v38", "label_noise", "trainclean_v3"],
                           "notes": f"recipe inherited verbatim from {src}; data.split and data.train_label_cutoff differ"},
            "data": {"split": SPLIT, "train_label_cutoff": CUTOFF}}}
        (OUT / f"{eid}.yaml").write_text(f"# v38: {eid} -- {src} trained without defect-log-v3 tier A, label tails cut.\n"
                                         "# Generated by scripts/make_v38_configs.py -- do not edit by hand.\n"
                                         + yaml.safe_dump(doc, sort_keys=False))
        ids.append(eid)
    frame, lstm, cf = ids
    queues = {"sweep_gpu0": [(frame, s) for s in SEEDS] + [(lstm, s) for s in SEEDS] + [(cf, 2)],
              "sweep_gpu1": [(cf, 0), (cf, 1)]}
    for q, runs in queues.items():
        (OUT / f"{q}.yaml").write_text(yaml.safe_dump(
            {"experiments": [{"config": f"configs/h7/v38/{n}.yaml", "seed": s} for n, s in runs]}, sort_keys=False))
    print(f"wrote {len(ids)} configs + {len(queues)} sweeps -> {OUT}")


if __name__ == "__main__":
    main()
