#!/usr/bin/env python
"""Generate the v30 SCE + auxiliary-branch configs.

Four one-change arms x three matched source/training seeds on the frozen v26 caches. Everything except the
auxiliary term is the completed v27 ``sce`` run of the same seed (identical encoder, framewise head, decoding,
optimiser recipe and cache), which is therefore the matched parent.

  python scripts/make_v30_configs.py
"""
from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "configs/h7/v30"
ARMS = {
    "change_contrastive": "pull same-phase frame pairs together, push pairs straddling a transition apart",
    "peak_count": "ordinal head: number of transitions in the last 8 frames (>=1, >=2)",
    "time_to_event": "regression head: log1p(frames until the next transition), censored after the last",
    "boundary": "binary head: first frame of a new phase (v27 boundary target, no diffusion, shared encoder)",
}

BASE = {
    "inherits": "configs/h7/v26/_base.yaml",
    "builder": "cached_video_validation_training",
    "cfg": {
        "experiment": {
            "id": "v30_base_do_not_run",
            "out_root": "runs/h7/v30",
            "tags": ["v30", "sce-aux", "patient-grouped", "trainval-only"],
            "notes": "v27 SCE plus one training-time auxiliary branch on frozen v26 visual features",
        },
        "data": {"input_mode": "visual", "sequence_mode": "full"},
        "model": {
            "type": "sce_aux_adapter",
            "backbone": {"name": "cached_features"},
            "head": {"name": "none"},
            "sce_aux": {"aux": "change_contrastive", "hidden": 96, "layers": 6, "intermediate_layers": [2, 4, 6],
                        "attention_reduction": 2, "dropout": 0.5},
            "num_classes": 16,
            "dropout": 0.5,
        },
        "loss": {"name": "sce_aux_objective", "aux": "change_contrastive", "semantic_weight": 0.8, "smooth_weight": 0.3,
                 "aux_weight": 0.5, "truncation": 4.0, "pair_offset": 2, "margin": 0.5, "window": 8, "cap": 64},
        "optimizer": {"name": "adamw", "lr": 0.0001, "weight_decay": 0.01},
        "scheduler": {"name": "cosine", "eta_min": 0.0},
        "training": {"epochs": 100, "batch_size": 1, "eval_len": 1024, "eval_stride": 1024, "eval_batch_size": 1024,
                     "num_workers": 0, "amp": True, "monitor": "p_t", "grad_accum": 8, "swa_last": 0},
    },
}


def _dump(path: Path, doc: dict, header: str) -> None:
    path.write_text(f"# {header}\n# Generated by scripts/make_v30_configs.py -- do not edit by hand.\n"
                    + yaml.safe_dump(doc, sort_keys=False))


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    _dump(OUT / "_base.yaml", BASE, "v30 SCE + one auxiliary branch: shared v27 SCE recipe, validation only")
    sweeps: dict[str, list] = {"gpu0": [], "gpu1": []}
    order = [(arm, src) for src in (0, 1, 2) for arm in ARMS]
    for i, (arm, src) in enumerate(order):
        name = f"{arm}_src{src}"
        doc = {
            "inherits": "configs/h7/v30/_base.yaml",
            "cfg": {
                "experiment": {"id": f"v30_{name}", "seed": src,
                               "tags": ["v30", arm, f"matched-source-seed-{src}", "trainval-only"], "notes": ARMS[arm]},
                "data": {"feature_cache": f"runs/h7/v26/features_seed{src}"},
                "model": {"sce_aux": {"aux": arm}},
                "loss": {"aux": arm},
            },
        }
        _dump(OUT / f"{name}.yaml", doc, f"v30 {arm}, matched source seed {src}. {ARMS[arm]}")
        sweeps["gpu0" if i % 2 == 0 else "gpu1"].append({"config": f"configs/h7/v30/{name}.yaml", "seed": src})
    for gpu, runs in sweeps.items():
        (OUT / f"sweep_{gpu}.yaml").write_text(yaml.safe_dump({"experiments": runs}, sort_keys=False))
    print(f"wrote {len(order)} run configs + base + 2 sweeps -> {OUT}")


if __name__ == "__main__":
    main()
