#!/usr/bin/env python3
"""Per-video defect log: what is wrong with each anomalous video, in words, with its evidence.

Merges the inspected labels (data/qc/nantes_video_defects_v1.json, one entry per video, written by
looking at the frames) with the measured evidence (results/hard_videos.json and
results/anomaly_log.json) and with where each video sits in every split, so a reader can see both
what the defect is and what it costs.

Writes results/defect_log.csv (machine-readable), results/defect_log.md (English), and
results/defect_log_vi.md (Vietnamese descriptions).

    PYTHONPATH=src python scripts/render_defect_log.py
"""
from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def split_roles(video: str) -> str:
    roles = []
    for name, label in (("nantes_grouped_v1", "grouped-v1"), ("nantes_grouped_v2", "grouped-v2")):
        d = json.loads((ROOT / f"data/splits/{name}.json").read_text())
        for part, vids in d["videos"].items():
            if video in vids:
                roles.append(f"{label}:{part}")
    tests = [f"fold{k}" for k in range(5)
             if any(r and r[0] == video and r[1] == "test"
                    for r in csv.reader(open(ROOT / f"data/splits/nantes_official/split{k}.csv")))]
    if tests:
        roles.append("official test in " + ",".join(tests))
    return "; ".join(roles)


def main() -> None:
    qc = json.loads((ROOT / "data/qc/nantes_video_defects_v1.json").read_text())
    hard = {r["video"]: r for r in json.loads((ROOT / "results/hard_videos.json").read_text())["flagged"]}
    auto = {r["video"]: r for r in json.loads((ROOT / "results/anomaly_log.json").read_text())["videos"]}
    cats = qc["categories"]
    rows = []
    for vid, e in qc["videos"].items():
        h, a = hard.get(vid, {}), auto.get(vid, {})
        rows.append({
            "video": vid, "defects": "+".join(e["defects"]),
            "what_is_wrong_en": " ".join(cats[c][0] for c in e["defects"]),
            "what_is_wrong_vi": " ".join(cats[c][1] for c in e["defects"]),
            "detail": e["note"],
            "found_by": "model scan + inspection" if vid in hard else "image scan + inspection",
            "best_frame_acc": h.get("best_acc"), "median_frame_acc": h.get("median_acc"),
            "n_configs": h.get("n_configs"), "median_onset_lag_h": a.get("median_lag_h"),
            "splits": split_roles(vid)})
    severity = ["blank_throughout", "no_division", "annotation_ahead", "abrupt_cleavage", "annotation_behind",
                "embryo_absent_late", "dark_frames", "out_of_focus_mid", "heavy_fragmentation", "out_of_focus_late"]
    rows.sort(key=lambda r: (min(severity.index(c) for c in r["defects"].split("+")), r["best_frame_acc"] if r["best_frame_acc"] is not None else 1))

    with open(ROOT / "results/defect_log.csv", "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0]))
        w.writeheader()
        w.writerows(rows)

    for lang, key, path in (("en", "what_is_wrong_en", "results/defect_log.md"),
                            ("vi", "what_is_wrong_vi", "results/defect_log_vi.md")):
        with open(ROOT / path, "w") as fh:
            title = "Anomalous videos: what is wrong with each" if lang == "en" else "Video bất thường: mỗi video bị lỗi gì"
            fh.write(f"# {title}\n\n")
            fh.write(f"Generated by `scripts/render_defect_log.py` from `data/qc/nantes_video_defects_v1.json`. "
                     f"{qc['method']}\n\n")
            head = ("| video | defect | what is wrong | detail | found by | best acc | splits |"
                    if lang == "en" else "| video | loại lỗi | bị lỗi gì | chi tiết | phát hiện bởi | acc tốt nhất | split |")
            fh.write(head + "\n|---|---|---|---|---|---|---|\n")
            for r in rows:
                acc = r["best_frame_acc"] if r["best_frame_acc"] is not None else "not evaluated held out"
                fh.write(f"| {r['video']} | {r['defects']} | {r[key]} | {r['detail']} | "
                         f"{r['found_by']} | {acc} | {r['splits']} |\n")

    from collections import Counter
    c = Counter(d for r in rows for d in r["defects"].split("+"))
    print(f"{len(rows)} videos, {sum(c.values())} defect labels")
    for k in severity:
        if c[k]:
            print(f"  {k:20} {c[k]:2d}  {cats[k][1]}")
    print("\nwrote results/defect_log.csv, results/defect_log.md, results/defect_log_vi.md")


if __name__ == "__main__":
    main()
